<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <NoWarn>MSB3277</NoWarn>
    <TargetFramework>net8.0</TargetFramework>
    <AssemblyName>D365CustomerService.Plugins</AssemblyName>
    <RootNamespace>D365CustomerService.Plugins</RootNamespace>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.CrmSdk.CoreAssemblies" Version="9.0.2.52" />
  </ItemGroup>

</Project>