<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net462</TargetFramework>
    <AssemblyName>D365CustomerService.Plugins</AssemblyName>
    <RootNamespace>D365CustomerService.Plugins</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.CrmSdk.CoreAssemblies" Version="9.0.2.52" />
  </ItemGroup>

</Project>